<Project Sdk="Microsoft.NET.Sdk.BlazorWebAssembly">

  <PropertyGroup>
    <TargetFramework>net10.0</TargetFramework>
    <Version>1.0.0</Version>
    <AssemblyName>MountainStates.MSSA.Client.Oqtane</AssemblyName>
    <StaticWebAssetProjectMode>Default</StaticWebAssetProjectMode>
    <BlazorWebAssemblyLoadAllGlobalizationData>true</BlazorWebAssemblyLoadAllGlobalizationData>
    <PublishTrimmed>false</PublishTrimmed>
    <BlazorEnableCompression>false</BlazorEnableCompression>
    <BlazorDisableThrowNavigationException>true</BlazorDisableThrowNavigationException>
  </PropertyGroup>

  <ItemGroup>
    <Compile Remove="Modules\MountainStates.MSSA.Module.MSSA_BackOfficeEntry\**" />
    <Compile Remove="Modules\MountainStates.MSSA.Module.MSSA_TrialSecretary\**" />
    <Content Remove="Modules\MountainStates.MSSA.Module.MSSA_BackOfficeEntry\**" />
    <Content Remove="Modules\MountainStates.MSSA.Module.MSSA_TrialSecretary\**" />
    <EmbeddedResource Remove="Modules\MountainStates.MSSA.Module.MSSA_BackOfficeEntry\**" />
    <EmbeddedResource Remove="Modules\MountainStates.MSSA.Module.MSSA_TrialSecretary\**" />
    <None Remove="Modules\MountainStates.MSSA.Module.MSSA_BackOfficeEntry\**" />
    <None Remove="Modules\MountainStates.MSSA.Module.MSSA_TrialSecretary\**" />
  </ItemGroup>

  <ItemGroup>
    <Compile Remove="Services\BackOfficeEntryService.cs" />
    <Compile Remove="Services\IBackOfficeEntryService.cs" />
    <Compile Remove="Services\ITrialSecretaryService.cs" />
    <Compile Remove="Services\MSSA_ExcelServerStartup.cs" />
    <Compile Remove="Services\TrialSecretaryService.cs" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly" Version="10.0.9" />
    <PackageReference Include="Microsoft.AspNetCore.Components.WebAssembly.Authentication" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Localization" Version="10.0.9" />
    <PackageReference Include="Microsoft.Extensions.Http" Version="10.0.9" />
  </ItemGroup>

  <ItemGroup>
    <ProjectReference Include="..\Shared\MountainStates.MSSA.Shared.csproj" />
  </ItemGroup>

  <ItemGroup>
    <PackageReference Include="Oqtane.Client" Version="10.2.1" />
  </ItemGroup>

</Project>
